name: Run the Release

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      environment:
        description: 'Environment to deploy'
        required: false
        default: 'staging'
  
permissions:
  contents: write

jobs:
  Create_Packages:
    name: Create Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: "REPO"

      - name: Make Directory Structure
        run: mkdir -p release

      - name: Build DEB Package
        run: |
          sudo apt install devscripts build-essential lintian dkms debhelper -y
          cd REPO
          export DEBFULLNAME="Glaolle"
          export DEBEMAIL="glaolle@gmail.com"
          cd ./haspd-aksparlnx-dkms
          debuild -us -uc -tc -b
          cd ..
          rm -f *.build* *.changes
          unset DEBEMAIL
          unset DEBFULLNAME
          #dpkg-deb --build SOURCES/${GITHUB_REPO_NAME} "${{ env.GITHUB_REPO_NAME }}_${{ env.VERSION }}_${{ env.DEB_ARCHITECTURE }}.deb"

      - name: Confirm builds complete
        run: |
          ls
          sudo install -m 644 -o runner -g runner $(find . -type f -name *.deb) release/

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: release/*
